### ISSUE TITLE
Bootstrapping with no "last_block_watcher" stops teosd from starting

### ISSUE THREAD

**Issue by orbitalturtle** [talaia-labs/python-teos#117]
Encountered a small bug, I think. I had run the watchtower daemon before & added a test appointment, so the second time it started bootstrapping from backed up data in teosd.py. But since I was using regtest, no blocks had been mined and no "last_block" had been added to the database.         

So the program trying to retrieve the last block on line 115 returns "None." Such a block doesn't exist, so the server shuts down

**Comment by sr-gi** [comment]
Indeed, this is a bug.

## Steps to reproduce

- Start bitcoind on regtest
- Start teosd on regtest
- Send an appointment to teos
- Restart teos without mining any block

## Description

Both the `Watcher` and `Responder` store the `last_known_block` after receiving a block. On a fresh bootstrap there is no `last_known_block`, so if the daemon is stop before a block is ever mined the entries are never created. When the tower restarts (now from backed up data) it tries to retrieve the `last_known_blocks` from the database but it does not find them.

## Background 

This is related to #92. Originally both the `Watcher` and the `Responder` queried the best chain tip before entering the main `do_watch` loop and stored them in the database. This became problematic after adding data persistence, since the tip cannot be naively updated or some block data can be missed:

- A `last_known_block` is loaded from the database
- The tower has fallen behind so it queries the new tip and starts catching up
    - A new best tip is found while updating (1 or more blocks have been mined)
- The towers is up to date with the last queried tip
- Both Watcher and Responder enter their main `do_watch` loop and query the best tip
- **All data between the last queried tip and the current tip has not been checked**

## Solution

I think a harmless solution would be to query `bestblockhash` on fresh boostrap in `teosd` and store it as the `last_knonw_block` os both the `Watcher` and `Responder` in the database. This way we ensure that nothing weird happens during a bootstrap from backed up data whilst fixing this. A better solution may be needed to fix #92 , but I think this should do for now.
