### ISSUE TITLE
TEOS-API.md Appointment Example uses blocks with a height over 1 million

### ISSUE THREAD

**Issue by josh-kean** [talaia-labs/python-teos#134]
Hi all,
I was going through the project's documentation and saw that the example for an appointment in the  TEOS-API.md file in the cli folder have block heights over 1 million.
Is there a reason for blocks of this height? I can see a scenario where somebody uses these block numbers instead of heights that are more reflective of the Bitcoin blockchain. 
I don't mind going in and lowering the block heights by 1 million. 

"start_time": 1568118,  
"end_time": 1568120,

**Comment by sr-gi** [comment]
Hey Josh, thanks for noticing that. [TEOS-API.md](https://github.com/talaia-labs/python-teos/blob/master/cli/TEOS-API.md) is a document that explained the underlaying API from when the server code was still not open source. The block heights it is referring to are from testnet, instead of mainnet, therefore why they are over 1M.

We're getting rid of the file in [the watchtower plugin branch](https://github.com/talaia-labs/python-teos/tree/watchtower-plugin/cli), since it serves no purpose anymore.

**Comment by josh-kean** [comment]
Hey sr-gi. That's good to know; I didn't realize it was based on the testnet, but that makes sense!
Thanks for alerting me to #133; I'll take a look at that pr and see what's new!
