### ISSUE TITLE
Clarify in docs which port should be used for watchtower-plugin

### ISSUE THREAD

**Issue by 3nprob** [talaia-labs/python-teos#268]
There is the "internal API", the "RPC port" and the "API".

9814 seems to be the "API port" confiured for both by default, but in reality it's the RPC port that should be connected to, I think?

**Comment by sr-gi** [comment]
Hey @3nprob.

I'm not sure I follow exactly what your issue is, even though I think the architecture docs can be improved indeed.  Here's a diagram of the interfaces.

![gRPC teos](https://user-images.githubusercontent.com/6665628/108374023-cc6a0a00-7200-11eb-812c-aad3fc56bbca.jpg)

In a nutshell, the HTTP API (used by the client) uses the port 9814 by default. This is the interface used by the `watchtower-plugin` to send data to the tower, but also by any other client implementation.

The gRPC interface is used by the tower administrator to interact with the tower (therefore it is not used by the `watchtower-plugin`, since the plugin is "a client").

Finally, the internal api is the joint interface used internally by the tower (only exposed to localhost). This is also a gRPC interface, so the HTTP requests are converted to gRPC and passed to the tower, and the RPC requests are mainly forwarded after some checks.

**Comment by 3nprob** [comment]
Thanks fpr the explanation, that explains a lot. Odd, though - I was not able to get the watchtower working that way, but did get it working when pointing it to the RPC port. All servies are running on 127.0.0.1.

teos running with:
```
        API_BIND = "127.0.0.1"
        API_PORT = 9814
        RPC_BIND = "127.0.0.1"
        RPC_PORT = 8432
```

first i tried this:
```
$ lightning-cli registertower $ID 127.0.0.1 9814
```

This adds the tower with the expected address, but all appointments are building up in pending and the client complains about not being able to connect. 
I also see nothing in the teos logs apart from the normal block processing.


then i tried this:
```
$ lightning-cli registertower $ID 127.0.0.1 8432
{
   "available_slots": 196,
   "public_key": "$ID",
   "subscription_expiry": ...,
   "subscription_signature": "...",
   "user_id": "..."
}
```

after which,
```
{
   "towers": [
      {
         "id": "$ID",
         "netaddr": "http://127.0.0.1:9814",
         "status": "reachable",
         "available_slots": 196,
         "pending_appointments": [],
         "invalid_appointments": []
      }
   ]
}
```

So the appoointments cleared out, and after this, it's processing appointments as expected. Logs are also showing up in teos now.

So it seems at least some intial setup over the rpc from the client is needed? 

(BTW, an aside, but is there any particular motivaion behid not exposing tower confirguation for the plugin under plugin config?)

**Comment by sr-gi** [comment]
Ohh wait! `RPC_BIND` and `RPC_PORT` refer to `teos` RPC, not to bitcoin RPC.

Looks like you're using the same RPC port for Bitcoin RPC and teos RPC, so something is not working properly.

Can you try to run it on a different port?

> (BTW, an aside, but is there any particular motivaion behid not exposing tower confirguation for the plugin under plugin config?)

I don't think I follow. Do you mean why the tower-plugin has it's own config? If so, it's because the tower is supposed to support multiple clients. The `watchtower-plugin` is just a client to work with c-lightning, but the tower is meant to work with other node implementations.

**Comment by 3nprob** [comment]
Aaah no, bitcoin RPC is running on a different non-default port, 8432 here does refer to teos RPC!

**Comment by 3nprob** [comment]
> I don't think I follow. Do you mean why the tower-plugin has it's own config? If so, it's because the tower is supposed to support multiple clients. The watchtower-plugin is just a client to work with c-lightning, but the tower is meant to work with other node implementations.

I mean, why can't we configure the plugin the clightning plugin option interface, as is customary? It should of course not come at the expense of the current (stand-alone config file) interface. https://github.com/ElementsProject/lightning/blob/master/doc/PLUGINS.md#types-of-options

If you have some reservations about that, would a resonable compromise to at least provide a plugin option to the path of said file?

**Comment by sr-gi** [comment]
Umm, I was completely unaware of this. Looks like something that could be added as replacement (or alternative) to the current plugin config.

**Comment by sr-gi** [comment]
I'll start tackling this Options enhancement.

I'm still super curious about the ports issue. Would you mind sharing the logs of that period if you still have them available?

Feel free to remove any IDs if you have any privacy concerns, I'm only really interested on the ports being reported by the tower and the ones the plugin was trying to connect to.

Also, feel free to send them to sergi@talaia.watch if you'd rather them not being posted here.

**Comment by sr-gi** [comment]
@3nprob could you give https://github.com/talaia-labs/python-teos/pull/273 a go? That should allow you to define the watchtower plugin params as c-lightning options.
