### ISSUE TITLE
config file documentation

### ISSUE THREAD

**Issue by svewa** [talaia-labs/python-teos#279]
I tried to create a config file, guessing to not include the double-dashes in front of the parameters worked, but teos complained about missing section headers ([bitcoind], as I found out from other sites via google).
A sample config file with all available parameters etc would be helpful.

**Comment by sr-gi** [comment]
Hi @svewa.

There's currently a sample config file at https://github.com/talaia-labs/python-teos/blob/master/teos/template.conf

That ones does not have all available options, since some are not even supposed to be changed in most cases. However, any option found in the [init file](https://github.com/talaia-labs/python-teos/blob/master/teos/__init__.py) can be overwritten via the config file.

The format for all options is lower case hyphened, e.g:

`API_BIND` (\_\_init\_\_.py) --> `api_bind = ` (teos.conf).

Regarding the config file sections, we use [configparser](https://docs.python.org/3/library/configparser.html), so at least one section is required. The section do not matter though, the sample config file only uses them for clarity sake. That means that a config file like the following should be valid:

```
[random_section]
btc_rpc_user = user
btc_rpc_password = passwd
btc_rpc_connect = localhost
btc_network = mainnet
btc_feed_protocol = tcp
btc_feed_connect = localhost
btc_feed_port = 28332
api_bind = localhost
api_port = 9814
rpc_bind = localhost
rpc_port = 8814
subscription_slots = 100
max_appointments = 1000000
expiry_delta = 6
min_to_self_delay = 20
polling_delta = 60
block_window_size = 10
```

**Comment by svewa** [comment]
Thanks for the details. Sorry for being blind - searched for teos.conf but now see that template.conf is even referenced in the readme.
